[package]
name = "fartvy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_rapier3d = { version = "*", features = [ "simd-stable", "debug-render-3d" ] }
log = { version = "*", features = ["max_level_debug", "release_max_level_warn"] }
noisy_bevy = "0.7.0"
rand = "0.8.5"
