name: Deploy to GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write  # This allows the workflow to push to gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install wasm-bindgen-cli
        run: cargo install wasm-bindgen-cli

      - name: Build for WASM
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Generate WASM bindings
        run: |
          wasm-bindgen target/wasm32-unknown-unknown/release/fartvy.wasm --out-dir out --target web --no-typescript

      - name: Create index.html
        run: |
          mkdir -p out
          echo '<!doctype html>
          <html lang="en">
          <body style="margin: 0px;">
            <script type="module">
              import init from "./fartvy.js";
              init().catch((error) => {
                if (!error.message.startsWith("Using exceptions for control flow, don'\''t mind me. This isn'\''t actually an error!")) {
                  throw error;
                }
              });
            </script>
          </body>
          </html>' > out/index.html

      - name: Copy static files
        run: |
          cp -r static/* out/ || echo "No static directory to copy from."

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          allow_empty_commit: false
          keep_files: false
          enable_jekyll: false
